- courses/intro-to-ada/intro_to_ada.rst
Mentioning non-generic packages first
> Reviewed section on numerics

- courses/intro-to-spark/book/02_Flow_Analysis.rst
- courses/intro-to-spark/book/04_State_Abstraction.rst
- courses/intro-to-spark/book/05_Proof_Of_Functional_Correctness.rst
Checked source-code examples on staging website
> Revised source-code examples

- courses/intro-to-spark/book/01_Overview.rst
- courses/intro-to-spark/book/02_Flow_Analysis.rst
- courses/intro-to-spark/book/03_Proof_Of_Program_Integrity.rst
- courses/intro-to-spark/book/04_State_Abstraction.rst
- courses/intro-to-spark/book/05_Proof_Of_Functional_Correctness.rst
At this time, there is no need anymore to emphasize the disctinction
between previous SPARK versions and current SPARK version.
> Cleanup for first 3 sections of SPARK course

- courses/intro-to-spark/book/01_Overview.rst
- courses/intro-to-spark/book/02_Flow_Analysis.rst
- courses/intro-to-spark/book/03_Proof_Of_Program_Integrity.rst
- courses/intro-to-spark/book/04_State_Abstraction.rst
- courses/intro-to-spark/book/05_Proof_Of_Functional_Correctness.rst
This is a complete second pass.
We need to update the run/prove widget to go further.
> Second pass over SPARK course

- courses/intro-to-spark/book/01_Overview.rst
> Address review comment

- courses/intro-to-spark/book/01_Overview.rst
- courses/intro-to-spark/book/02_Flow_Analysis.rst
- courses/intro-to-spark/book/03_Proof_Of_Program_Integrity.rst
- courses/intro-to-spark/book/04_State_Abstraction.rst
- courses/intro-to-spark/book/05_Proof_Of_Functional_Correctness.rst
> take into account feedback from Claire & Boris

- courses/intro-to-ada/chapters/subprograms.rst
Moved inline comment from reviewer.
> Editorial change: fixed admonition

- index.rst
Following up on #51.
I don't know how to check if this looks good on the website.
> Run button and slightly more complex example code on first page

- .gitmodules
- engine/Makefile
- engine/sphinx/conf.py
- engine/sphinx/learn_theme/static/css/common.css
- engine/sphinx/learn_theme/static/js/editors.js
And make the Makefile clone the ACE editor as needed.
> Import static files from the cloudserver to here

- engine/sphinx/learn_theme/static/js/editors.js
... when the cloudchecker is not responding in time.
> enhance degraded mode

- courses/intro-to-ada/chapters/generics.rst
> Editorial change: fixed ada-role

- courses/advanced-spark/chapters/concurrency.rst
- courses/advanced-spark/chapters/ghost_code.rst
- courses/advanced-spark/chapters/object_oriented_programming.rst
- courses/advanced-spark/chapters/subprogram_contracts.rst
- courses/advanced-spark/chapters/systems_programming.rst
- courses/advanced-spark/chapters/test_and_proof.rst
- courses/advanced-spark/chapters/type_contracts.rst
- courses/intro-to-ada/chapters/exceptions.rst
- courses/intro-to-spark/book/03_Proof_Of_Program_Integrity.rst
- courses/intro-to-spark/book/04_State_Abstraction.rst
- courses/intro-to-spark/book/05_Proof_Of_Functional_Correctness.rst
Issues detected by Travis-CI test using GNAT Community 2018
> Editorial changes due to test issues

- books/SPARK_for_the_MISRA_C_Developer/chapters/01_preface.rst
- books/SPARK_for_the_MISRA_C_Developer/chapters/02_program_consistency.rst
- books/SPARK_for_the_MISRA_C_Developer/chapters/03_syntactic_guarantees.rst
- books/SPARK_for_the_MISRA_C_Developer/chapters/04_strong_typing.rst
- books/SPARK_for_the_MISRA_C_Developer/chapters/05_initialization.rst
- books/SPARK_for_the_MISRA_C_Developer/chapters/06_side_effects.rst
- books/SPARK_for_the_MISRA_C_Developer/chapters/07_undefined_behavior.rst
- books/SPARK_for_the_MISRA_C_Developer/chapters/08_unreachable_and_dead_code.rst
- books/SPARK_for_the_MISRA_C_Developer/chapters/09_conclusion.rst
- books/SPARK_for_the_MISRA_C_Developer/chapters/10_references.rst
- books/SPARK_for_the_MISRA_C_Developer/index.rst
Here is the initial draft.
I compiled locally with a custom ReST project, I did not understand how to integrate with how books are generated on the learning website.
I am using code-block for both C and Ada, with the inexistent attribute spark-prove that indicates a snippet where I'd like GNATprove to run in proof mode.
We'll also want to adapt the widget so that we can extract a physical book from the online version, where the results of compilation/run/analysis are displayed as needed.
> Initial draft of a book on SPARK for MISRA-C developers

- books/Ada_For_The_CPP_Java_Developer/chapters/05_Type_System.rst
- books/Ada_For_The_CPP_Java_Developer/chapters/08_Classes_and_Object_Oriented_Programming.rst
- books/Ada_For_The_CPP_Java_Developer/chapters/09_Generics.rst
- books/Ada_For_The_CPP_Java_Developer/chapters/11_Concurrency.rst
- courses/advanced-ada/chapters/generics.rst
- courses/advanced-ada/chapters/interfacing_with_cpp.rst
- courses/intro-to-ada/chapters/contracts.rst
- courses/intro-to-ada/chapters/introduction.rst
Based on the logfile from Travis CI test
> Editorial changes: fixing warnings for HTML generation

- courses/intro-to-ada/chapters/more_about_types.rst
> Corrected ASCII value

- courses/intro-to-ada/chapters/imperative_language.rst
> Editorial change: removed duplicated word

- courses/advanced-ada/advanced_topics.rst
The list of topics is not supposed to be complete.
> Added basic structure of Advanced Ada course

- courses/intro-to-ada/chapters/generics.rst
Added constant for min. value of stack container.
Added exceptions.
Fixed issue #146.
> Improved source-code example for Stack

- courses/intro-to-ada/chapters/contracts.rst
- courses/intro-to-ada/chapters/object_oriented_programming.rst
- courses/intro-to-ada/chapters/standard_library.rst
- courses/intro-to-ada/chapters/tasking.rst
> Editorial changes: fixed typos

- courses/intro-to-ada/chapters/standard_library.rst
> Added comment for declarations in source-code snippets

- courses/advanced-ada/chapters/strong_typing.rst
- courses/advanced-spark/chapters/object_oriented_programming.rst
Reusing Gems 82 and 83:
- https://www.adacore.com/gems/gem-82
- https://www.adacore.com/gems/gem-83
> Added section on type-based security

- courses/advanced-ada/chapters/limited_types.rst
Reusing Gems #1, #2, #3, #10, #11, #12:
- https://www.adacore.com/gems/gem-1
- https://www.adacore.com/gems/gem-2
- https://www.adacore.com/gems/gem-3
- https://www.adacore.com/gems/ada-gem-10
- https://www.adacore.com/gems/ada-gem-11
- https://www.adacore.com/gems/ada-gem-12
> Added section on aggregates and return objects for limited types

- courses/advanced-ada/chapters/typing.rst
- internal/planning/advanced_ada.rst
- internal/planning/material_reuse.rst
Reusing Gem #50: https://www.adacore.com/gems/gem-50
> Added section on overloading resolution

- courses/advanced-ada/chapters/access_types.rst
- internal/planning/material_reuse.rst
Reusing Gems 23, 24, 33, 41 and 44.
> Added sections on access types

- courses/intro-to-ada/chapters/arrays.rst
- courses/intro-to-ada/chapters/modular_programming.rst
- courses/intro-to-ada/chapters/strongly_typed_language.rst
- courses/intro-to-ada/chapters/subprograms.rst
Hello,
This corrects minor typos in chapters 3, 5, 6 and 7.
Best,
Christophe
> Typos sections 3, 5, 6 and 7

- courses/intro-to-ada/chapters/introduction.rst
Moved and rephrased old AI;
Fixed issue #172
> Editorial change: fixed formatting of bullet points

- courses/advanced-ada/chapters/generics.rst
- internal/planning/advanced_ada.rst
This includes partial parametrization.
> Added section on formal packages and parametrization

- courses/intro-to-spark/book/03_Proof_Of_Program_Integrity.rst
Examples lead to many unproved checks. Now simplified and fixed.
> S115-009 Fix examples 6-7-8 in chapter 3 of intro to SPARK

- engine/sphinx/widget_extension.py
Aligning behavior with "run button"
> Added support for "prove button" in individual source-code snippets

- internal/posts/2019-01-08_proving-memory-operations-a-spark-journey.rst
This is a proof-of-concept, no detailed review is required.
The idea is to evaluate publishing of blog-posts integrally in the learning website and adding source-code snippets that can be executed / proved by the reader.
> Initial commit of blog-post as learning material

- courses/intro-to-ada/chapters/arrays.rst
- courses/intro-to-ada/chapters/contracts.rst
- courses/intro-to-ada/chapters/exceptions.rst
- courses/intro-to-ada/chapters/generics.rst
- courses/intro-to-ada/chapters/imperative_language.rst
- courses/intro-to-ada/chapters/more_about_types.rst
- courses/intro-to-ada/chapters/object_oriented_programming.rst
- courses/intro-to-ada/chapters/standard_library.rst
- courses/intro-to-ada/chapters/strongly_typed_language.rst
- courses/intro-to-ada/chapters/subprograms.rst
- courses/intro-to-ada/chapters/tasking.rst
- engine/Makefile
- engine/sphinx/learn_theme/static/js/editors.js
- engine/sphinx/widget_extension.py
Prepare the grounds for:
- moving the logic for determining the main completely to the back-end
- adding any number of new button types, needed for the upcoming labs and books.
> Preparation for engine improvements

- books/SPARK_for_the_MISRA_C_Developer/chapters/02_program_consistency.rst
- books/SPARK_for_the_MISRA_C_Developer/chapters/04_strong_typing.rst
- courses/intro-to-ada/chapters/privacy.rst
- engine/sphinx/widget_extension.py
And a minor adjustment to the Ada course.
Add support for performing custom gnatchop for code snippets
where gnatchop would complain.
> Minor adjustment to the SPARK/MISRA C book

- CONTRIBUTING.md
- engine/sphinx/widget_extension.py
For the button modes, and for the manual_chop mechanism.
> Add documentation

- courses/advanced-ada/chapters/oo_prog.rst
- internal/planning/material_reuse.rst
Chapter: Object-Oriented Programming
> Added section on "Extending Interfaces" and on "Calling inherited subprograms"

- books/SPARK_for_the_MISRA_C_Developer/chapters/06_side_effects.rst
Correct the quote to close off the code fragment.
> Fix Issue #201

- labs/intro-to-ada/chapters/imperative_language.rst
Chapter: "Imperative language"
>  Labs: draft version of exercise #1

- courses/intro-to-ada/chapters/arrays.rst
- courses/intro-to-ada/chapters/modular_programming.rst
- courses/intro-to-ada/chapters/subprograms.rst
- courses/intro-to-ada/index.rst
Editorial changes for "Intro to Ada" course.
> Editorial changes: moved chapters on subprograms and modular programming

- labs/intro-to-ada/chapters/imperative_language.rst
- labs/intro-to-ada/chapters/solutions.rst
Fixing problem reported in #256.
> Labs: simplified exercise

- courses/SPARK_for_the_MISRA_C_Developer/chapters/02_program_consistency.rst
- courses/SPARK_for_the_MISRA_C_Developer/chapters/03_syntactic_guarantees.rst
- courses/SPARK_for_the_MISRA_C_Developer/chapters/04_strong_typing.rst
- courses/SPARK_for_the_MISRA_C_Developer/chapters/05_initialization.rst
- courses/SPARK_for_the_MISRA_C_Developer/chapters/06_side_effects.rst
Exploiting new button prove_flow_report_all_button
Also adds a flow button where there would be no button at all.
> Various fixes related to new engine and widgets

- .travis.yml
- engine/Makefile
- engine/travis_install.sh
Updating to GNAT Community 2019;
Improving Travis-CI setup script;
Adding new courses to Makefile.
> Improvements to test environment

- .travis.yml
- engine/Makefile
- engine/tests/compile_blocks.py
- engine/travis_install.sh
Updating test environment to use Python 3 and new URL for GNAT installer
> Tests: updates for Python 3 and URLs

- engine/sphinx/widget_extension.py
Avoiding Latex code in case of HTML output
> Widget: fixing HTML output

- labs/intro-to-ada/chapters/solutions.rst
- labs/intro-to-ada/chapters/subprograms.rst
Covering: conditional expressions, "in out" parameter mode.
> Labs: adding new exercises based on simple state machine

- courses/intro-to-ada/chapters/object_oriented_programming.rst
New sections to chapter on "Object-Oriented Programming":
- private/limited types;
- classwide access types.
> OO prog: adding new sections

- courses/intro-to-ada/chapters/contracts.rst
- courses/intro-to-ada/chapters/standard_library_dates_times.rst
Adding links to unbounded strings and dates for further information.
> Including links to other sections

- courses/intro-to-ada/chapters/generics.rst
> Editorial change: corrected phrase

- courses/intro-to-ada/chapters/appendices.rst
- courses/intro-to-ada/chapters/standard_library_containers.rst
- courses/intro-to-ada/chapters/standard_library_dates_times.rst
- courses/intro-to-ada/chapters/standard_library_files_streams.rst
- courses/intro-to-ada/chapters/standard_library_numerics.rst
- courses/intro-to-ada/chapters/standard_library_strings.rst
> Minor improvements in standard library chapters

- .travis.yml
- backend/REQUIREMENTS.txt
- backend/app/widget/reporter.py
- backend/app/widget/widget_routes.py
- frontend/Makefile
Fixing a few issues:
- Makefile target issues causing travis CI failures
- A timeout issue causing amqp connection timeout issues in the backend.
> Rmq timeout fix

- frontend/Makefile
- frontend/src/styles/learn.scss
Fixing rendering issue reported in #316
> Fixing stdout rendering

- backend/.flaskenv
- backend/app/widget/project.py
- frontend/src/styles/learn.scss
- frontend/src/ts/widget.ts
Its still hacky but now if the algorithm detects more than one Ada body without a corresponding package, it will look for one of the files to be called main.adb and it will use that one. If none are named main.adb, it will not have a main. If more than one is named main.adb it will throw an exception.
> Modifying Ada main detection algorithm

- backend/app/widget/file.py
- backend/app/widget/project.py
- content/courses/SPARK_for_the_MISRA_C_Developer/chapters/03_syntactic_guarantees.rst
- frontend/src/ts/editor.ts
- frontend/src/ts/strings.ts
Testing compile button support. Fixing a few typo errors. Adding build success feedback from backend.
This completes enhancement #254
> Compile button

- frontend/src/styles/learn.scss
Making output_area scrollable with fixed max height.
> Fixing excessive Put_Line noise crashing page rendering

- backend/app/widget/container.py
- backend/app/widget/reporter.py
- backend/bootstrap.sh
- frontend/src/ts/comms.ts
- frontend/src/ts/types.ts
- frontend/src/ts/widget.ts
- frontend/yarn.lock
Handling errors in recursive polling function. Fixing run of C program. Adding clickable divs to C program build errors. Adding maximum limit to number of requests to avoid infinite spinning in case of server lock up.
> Cleanup of build/run outputs

- backend/app/widget/tasks.py
- content/courses/intro-to-spark/chapters/02_Flow_Analysis.rst
- content/courses/intro-to-spark/chapters/04_State_Abstraction.rst
- frontend/src/ts/strings.ts
- frontend/yarn.lock
This PR completes enhancement request #236
> Fixing Issues/236

- backend/app/widget/container.py
- backend/app/widget/tasks.py
Increasing container memory cap to 256 after seeing gprbuild use more than 32MB for small-ish compilations.
> Increasing container memory cap

- content/labs/intro-to-ada/chapters/solutions.rst
- content/labs/intro-to-ada/chapters/standard_library_strings.rst
- content/labs/intro-to-ada/index.rst
Duplicated / adapted lab for date/times
> Adding lab for unbounded strings

- content/courses/intro-to-ada/chapters/subprograms.rst
> Editorial changes: resetting code accumulator

- content/courses/intro-to-ada/chapters/standard_library_containers.rst
Issue: https://github.com/AdaCore/learn/issues/365
> Matched the  and  and or operators to their respective correct set operation

- content/courses/intro-to-ada/chapters/standard_library_dates_times.rst
Issue: https://github.com/AdaCore/learn/issues/368
> Make benchmarking delay consistent between program and text (Intro to Ada course)

- content/courses/Ada_For_The_C_Embedded_Developer/chapters/02_Perspective.rst
- content/courses/Ada_For_The_C_Embedded_Developer/chapters/03_Concurrency.rst
- content/courses/Ada_For_The_C_Embedded_Developer/chapters/04_Embedded.rst
- content/courses/Ada_For_The_C_Embedded_Developer/chapters/05_SPARK.rst
- content/courses/Ada_For_The_C_Embedded_Developer/chapters/06_Translation.rst
- content/courses/Ada_For_The_C_Embedded_Developer/chapters/07_Reusability.rst
- content/courses/Ada_For_The_C_Embedded_Developer/chapters/08_Performance.rst
Also: correcting some bugs in the examples
> Adapting source-code examples to use widget

- frontend/src/ts/widget.ts
> Splitting multiline server responses for individual processing.

- content/courses/SPARK_for_the_MISRA_C_Developer/chapters/02_program_consistency.rst
- frontend/sphinx/widget_extension.py
- frontend/src/ts/widget.ts
> Fix for issue #391

- content/courses/intro-to-ada/chapters/more_about_types.rst
Spelling error: using _that_ instead of _than_ for a comparison.
> Changed "that" to "than".

- frontend/yarn.lock
Address current dependabot alert regarding CVE-2020-7720.
> Upgrading deps to bring node-forge to version 0.10.0.

- content/courses/intro-to-ada/chapters/strongly_typed_language.rst
Fixing issue reported in #412.
> Correcting conversion formula (meters to miles)

- content/courses/Ada_For_The_CPP_Java_Developer/chapters/05_Type_System.rst
> Adding missing parenthesis

- content/courses/intro-to-ada/chapters/arrays.rst
- content/courses/intro-to-ada/chapters/modular_programming.rst
- content/courses/intro-to-ada/chapters/more_about_types.rst
- content/courses/intro-to-ada/chapters/records.rst
- content/courses/intro-to-ada/chapters/subprograms.rst
Fixing issue reported in #413.
> Moving section on renaming of record components

- frontend/package.json
- frontend/src/ts/areas.ts
- frontend/src/ts/editor.ts
- frontend/src/ts/widget.ts
- frontend/tests/ts/areas.spec.ts
This uses ace editor's gutter annotations feature to add gutter annotations based on server feedback. Info messages will add a little "i" symbol next to lines with info messages (see SPARK courses for examples). Warnings will add a little yellow triangle. Errors will add a red x. All icons have mouse over text which indicates the error message reported by the server.
> Ace gutter annotations

- content/courses/Ada_For_The_C_Embedded_Developer/chapters/05_SPARK.rst
and make various other refinements in text
> apply new switch capability to disable integer overflow checks 

- content/courses/intro-to-embedded-sys-prog/chapters/conclusion.rst
- content/courses/intro-to-embedded-sys-prog/chapters/handling_interrupts.rst
- content/courses/intro-to-embedded-sys-prog/chapters/interacting_with_devices.rst
- content/courses/intro-to-embedded-sys-prog/chapters/introduction.rst
- content/courses/intro-to-embedded-sys-prog/chapters/low_level_programming.rst
- content/courses/intro-to-embedded-sys-prog/chapters/multi_language_development.rst
- content/courses/intro-to-embedded-sys-prog/conf.txt
- content/courses/intro-to-embedded-sys-prog/index.rst
- frontend/Makefile
- frontend/sphinx/conf.py
Initial structure of the upcoming Introduction to Embedded Systems Programming
course.
> Initial commit: Introduction to Embedded Systems Programming course

- content/courses/Ada_For_The_C_Embedded_Developer/index.rst
> Editorial change: correcting typo.

- content/courses/Ada_For_The_C_Embedded_Developer/chapters/04_Embedded.rst
> Editorial changes: adding buttons to examples

- content/courses/Ada_For_The_C_Embedded_Developer/chapters/02_Perspective.rst
> Adding explanation about arbitrary range of array types

- content/courses/Ada_For_The_C_Embedded_Developer/chapters/02_Perspective.rst
- content/courses/Ada_For_The_C_Embedded_Developer/chapters/07_Reusability.rst
> Editorial change: adding reference to section about generics.

- frontend/Makefile
- frontend/tests/compile_blocks.py
- Adding support for using `chop` module from widget.
- Adding support for manual chopping.
- Adding support for C-code compilation.
- Adding support for main file indicator.
- Correcting behavior of main file selection for a block.
- Adding support for compile and run buttons.
- Extending support for Sphinx classes ("c-nocheck", "ada-norun").
- Extending test with new consistency checks.
> Test script: various enhancements.

- content/labs/intro-to-ada/chapters/arrays.rst
- content/labs/intro-to-ada/chapters/more_about_types.rst
- content/labs/intro-to-ada/chapters/records.rst
- content/labs/intro-to-ada/chapters/standard_library_containers.rst
- content/labs/intro-to-ada/chapters/standard_library_dates_times.rst
- content/labs/intro-to-ada/chapters/standard_library_numerics.rst
- content/labs/intro-to-ada/chapters/strongly_typed_language.rst
- content/labs/intro-to-ada/chapters/subprograms.rst
- content/labs/intro-to-ada/chapters/tasking.rst
General comments:
- Can we make code that isn't meant to be changed read-only.
- When comparing the user's output and the expected output, can we use a diff that highlights errors (easier to find whitespace errors, etc.)
- Would adding links to relevant resources applicable to the lab improve usability?
- Can we add a dialog box that prevents the user from accidentally navigating away from the page and losing their implementation?
- Can we change the embedded editors auto-complete functionality? Specifically when using the tick operator it tends to add a second tick which might frustrate the user.
- When the test output is displayed after submission, newlines are shown as spaces. This makes it difficult to determine white space errors in several exercises.
- The content should be reviewed …
> Intro to ada lab review

- content/courses/intro-to-ada/chapters/imperative_language.rst
Clean up formatting for this page:
- Make the last `I` match the previous.
- Replace the difficult to read "'" with `'`, matching the format of a later chapter discussing attributes.
> Clean up formatting

- frontend/requirements.txt
Python: adding fixed versions for all packages.
Fixed #515.
> Fixing failing test issues.

- content/courses/Ada_For_The_Embedded_C_Developer/chapters/06_Translation.rst
Converting subsections to sections.
> Editorial change: simplifying chapter structure.

- .github/workflows/codeql-analysis.yml
Moving CodeQL frequency to only run on PR so that we don't hit the API rate limit issue.
> Changing CodeQL freq

- .github/workflows/sphinx-plugin-tests.js.yml
Changing frequency of GA for sphinx plugin tests.
> Optimizing GA for widget plugin tests

- .github/workflows/typescript-tests.js.yml
Changing action to only trigger on a push that includes changes to typescript files in the frontend directory or a pull_request on master.
> Optimization of ts action

- content/courses/intro-to-ada/chapters/more_about_types.rst
> Adding example of default values for discriminants.

- content/courses/intro-to-embedded-sys-prog/chapters/low_level_programming.rst
> remove duplicate text re: querying storage_size for access types

- frontend/tests/compile_blocks.py
> Adding fix to process last source-code block.

- content/courses/SPARK_for_the_MISRA_C_Developer/chapters/04_strong_typing.rst
- content/courses/SPARK_for_the_MISRA_C_Developer/chapters/07_undefined_behavior.rst
Fixing compile-time warnings about code style.
> Editorial changes in source-code examples.

- content/courses/advanced-ada/chapters/access_types.rst
- content/courses/advanced-ada/chapters/arrays.rst
- content/courses/advanced-ada/chapters/elaboration_of_generics.rst
- content/courses/advanced-ada/chapters/generics.rst
- content/courses/advanced-ada/chapters/initialization.rst
- content/courses/advanced-ada/chapters/limited_types.rst
- content/courses/advanced-ada/chapters/numerics.rst
- content/courses/advanced-ada/chapters/oo_prog.rst
- content/courses/advanced-ada/chapters/package_elaboration.rst
- content/courses/advanced-ada/chapters/statements.rst
- content/courses/advanced-ada/chapters/strong_typing.rst
- content/courses/advanced-ada/chapters/subprograms.rst
- content/courses/advanced-ada/conf.txt
- content/courses/advanced-ada/index.rst
Integrating suggestions from @bobduff
> Updates to outline of "Advanced Ada" course

- backend/app/widget/widget_routes.py
AWS Load balancer can use this route to check backend server health.
TN: U507-032
> Add a GET / route to backend

- content/courses/Ada_For_The_Embedded_C_Developer/chapters/03_Concurrency.rst
- frontend/sphinx/conf.py
Fixing runtime output of source-code examples in the PDF version of the "Ada for the Embedded C Prog." course.
> Fixing runtime output of code examples

- content/courses/advanced-ada/chapters/strong_typing.rst
- content/courses/intro-to-ada/chapters/modular_programming.rst
- content/courses/intro-to-ada/chapters/more_about_types.rst
- content/courses/intro-to-ada/chapters/privacy.rst
- content/courses/intro-to-ada/chapters/subprograms.rst
- content/courses/intro-to-ada/chapters/tasking.rst
- frontend/tests/compile_blocks.py
Doing some refactoring of the "compile blocks" script.
Aligning with some of the build configuration used by the backend for the online widget.
Fixing some minor issues in the script and in the content.
> Test script: improving compile blocks script.

- .github/workflows/sphinx-content-tests.js.yml
- README.md
- Vagrantfile
- frontend/Makefile
- Vagrant: introducing epub VM;
- GitHub Actions: adding test of complete site content generation and storing HTML content as artifact;
- Makefile: adding "test_content" to site content generation target.
> Frontend: improvements for site publication

- content/courses/intro-to-spark/chapters/02_Flow_Analysis.rst
- content/courses/intro-to-spark/chapters/03_Proof_Of_Program_Integrity.rst
- content/courses/intro-to-spark/chapters/04_State_Abstraction.rst
- content/courses/intro-to-spark/chapters/05_Proof_Of_Functional_Correctness.rst
> Use distinct widget projects for source-code examples

- .github/workflows/sphinx-books-tests.js.yml
- Vagrantfile
- frontend/Makefile
- frontend/requirements.txt
- frontend/sphinx/_epub_theme/epub-cover.html
- frontend/sphinx/_epub_theme/layout.html
- frontend/sphinx/_epub_theme/static/epub.css_t
- frontend/sphinx/_epub_theme/static/graphviz.css_t
- frontend/sphinx/_epub_theme/static/pygments.css_t
- frontend/sphinx/_epub_theme/theme.conf
- frontend/sphinx/conf.py
- frontend/sphinx/widget_extension.py
- Fix source-code examples in EPUB books (code size, preambles)
- Add support for cover page
- Add support for custom CSS files
- Fix various issues with CSS files
- Fix various issues related to HTML output for EPUB format
> epub books: various fixes and improvements

- .github/workflows/sphinx-books-tests.js.yml
- .github/workflows/sphinx-content-tests.js.yml
- .github/workflows/sphinx-plugin-tests.js.yml
- .github/workflows/typescript-tests.js.yml
> GitHub actions: freezing Python version

- content/index.rst
- frontend/src/styles/learn.scss
Combining three sections into single section with one download button per format
(per e-book).
> Frontpage: improving layout of e-books section

- content/courses/intro-to-ada/chapters/records.rst
> Fixing syntax error in source-code example

- frontend/Makefile
> Makefile: fixing support for hidden books

- content/courses/advanced-ada/chapters/modular_prog.rst
- content/courses/advanced-ada/chapters/package_elaboration.rst
- content/courses/advanced-ada/chapters/packages.rst
- content/courses/advanced-ada/chapters/subprograms_modularity.rst
- content/courses/advanced-ada/chapters/types.rst
Adding sections on:
- Package renaming
- Private packages
- Private subprograms
> Adding sections on package renaming, private packages and private subprograms

- content/courses/intro-to-ada/chapters/arrays.rst
- content/courses/intro-to-ada/chapters/generics.rst
- content/courses/intro-to-ada/chapters/privacy.rst
- content/labs/intro-to-ada/chapters/arrays.rst
- content/labs/intro-to-ada/chapters/exceptions.rst
- content/labs/intro-to-ada/chapters/modular_programming.rst
- content/labs/intro-to-ada/chapters/more_about_types.rst
- content/labs/intro-to-ada/chapters/records.rst
- content/labs/intro-to-ada/chapters/solutions.rst
- content/labs/intro-to-ada/chapters/strongly_typed_language.rst
Hi, this request is for typos or similar things I spotted.
> Fixing minor issues

- Vagrantfile
> VM: pinning to correct Ubuntu VM version

- frontend/requirements.txt
Pointing to commit that fixes highlighting issues with Ada aspects.
> Python: updating dev. version of Pygments

- content/courses/advanced-ada/chapters/packages.rst
- content/courses/intro-to-ada/chapters/modular_programming.rst
Adding sections:
- "Use type clause"
- "Use clauses and naming conflicts"
> Adding sections on use type clause and on naming conflicts

- content/courses/intro-to-ada/chapters/access_types.rst
> Removing incorrect access type conversion

- content/courses/Ada_For_The_Embedded_C_Developer/chapters/06_Translation.rst
> Adding comments on well-defined behavior of Unchecked_Conversion

- content/courses/intro-to-ada/chapters/subprograms.rst
> Adding simple explanation about .ads/.adb files

- content/courses/advanced-ada/chapters/access_types.rst
Duplicated section due to error during merge.
> Editorial change: removing duplicated section

- frontend/src/ts/widget.ts
Apologies, this was something that I broke in my updates
> Fix race condition that cause lab results to not be displayed

- frontend/sphinx/widget/templates/widget.html
- frontend/src/index.ts
- frontend/src/styles/learn.scss
- frontend/tests/ts/widget.spec.ts
Fixing issue with Google Translate.
> HTML: changing widget block to pre block

- content/courses/advanced-ada/chapters/limited_types.rst
- Adding section on limited private types
- Adding section on deriving from limited types
- Adding section on record components of limited type
> Adding multiple sections on limited types

- content/courses/advanced-ada/chapters/contracts.rst
- content/courses/advanced-ada/chapters/types.rst
Moving section "Stable Properties of a Type" to chapter on contracts.
> Editorial change: moving section

- content/courses/advanced-ada/chapters/aggregates.rst
New sections:
- Record aggregates
- Array aggregates
> Editorial change: adding new sections

- frontend/package.json
- frontend/yarn.lock
This reverts commit da79d34ca0c607a4ec504bc4081e5fda677cf9fd.
> Revert "Bump webpack from 5.75.0 to 5.76.0 in /frontend"

- content/courses/advanced-ada/parts/abstraction-oriented_prog/generics.rst
- content/courses/advanced-ada/parts/abstraction-oriented_prog/oo_prog.rst
- content/courses/advanced-ada/parts/abstraction-oriented_prog/strong_typing.rst
- content/courses/advanced-ada/parts/appendices/legacy.rst
- content/courses/advanced-ada/parts/control_flow/exceptions.rst
- content/courses/advanced-ada/parts/control_flow/expressions.rst
- content/courses/advanced-ada/parts/control_flow/statements.rst
- content/courses/advanced-ada/parts/control_flow/subprograms.rst
- content/courses/advanced-ada/parts/data_types/aggregates.rst
- content/courses/advanced-ada/parts/data_types/arrays.rst
- content/courses/advanced-ada/parts/data_types/numerics.rst
- content/courses/advanced-ada/parts/data_types/strings.rst
- content/courses/advanced-ada/parts/data_types/types.rst
- content/courses/advanced-ada/parts/data_types/types_representation.rst
- content/courses/advanced-ada/parts/modular_prog/packages.rst
- content/courses/advanced-ada/parts/modular_prog/subprograms_modularity.rst
- content/courses/advanced-ada/parts/resource_management/access_types.rst
- content/courses/advanced-ada/parts/resource_management/limited_types.rst
Adding part and section names to the project field of code examples from the "Advanced Ada" course.
> Editorial change: improving structure of code examples

- frontend/src/styles/learn.scss
Previous color scheme was difficult to read.
Refers to issue #828.
> Frontend: improving colors in sidebar

- content/courses/Ada_For_The_CPP_Java_Developer/chapters/05_Type_System.rst
Adding character escape to circumvent Sphinx issue.
This fixes #804.
> Editorial change: fixing special characters

- frontend/src/styles/learn.scss
> CSCC: further improvements to menu (#828)

- content/courses/SPARK_for_the_MISRA_C_Developer/chapters/03_syntactic_guarantees.rst
Adding function specification.
This fixes #762.
> Minor change: fixing compilation

- README.md
- content/courses/intro-to-ada/chapters/arrays.rst
- content/courses/intro-to-ada/chapters/modular_programming.rst
- content/courses/intro-to-ada/chapters/strongly_typed_language.rst
- content/courses/intro-to-ada/chapters/subprograms.rst
this PR fixes some typos, formatting, and inconsistency (e.g type-level appeared in both type-level and type level shapes) errors
> minor fixes

- frontend/webpack.dev.js
Avoiding issues with some Sphinx plug-ins, such as plantuml.
> Frontend: deactivating parallelism

- content/courses/intro-to-ada/chapters/interfacing_with_c.rst
- content/courses/intro-to-ada/chapters/standard_library_containers.rst
- content/courses/intro-to-ada/chapters/standard_library_dates_times.rst
- content/courses/intro-to-ada/chapters/standard_library_files_streams.rst
Minor typos found during review of Intro to Ada material
> Minor typos

- frontend/src/styles/learn.scss
> SCSS: adding scrollbar to side navigation (TOC)

- content/courses/ada-idioms/chapters/accommodating_future_enhancements.rst
- content/courses/ada-idioms/chapters/constructor_functions_for_type_extensions.rst
- content/courses/ada-idioms/chapters/fundamental_idioms_for_packages.rst
- content/courses/ada-idioms/chapters/reducing_object_code_from_generic_package_instantiations.rst
- content/courses/ada-idioms/index.rst
- content/courses/advanced-ada/parts/data_types/types_representation.rst
These chapters are based on documents written by Patrick Rogers; the content was adapted to the Sphinx-doc format.
> Adding chapters on package-related idioms

- content/courses/advanced-ada/parts/control_flow/subprograms.rst
- content/courses/advanced-ada/parts/data_types/types_representation.rst
- content/courses/advanced-ada/parts/resource_management/access_types.rst
Adding sections: 
- addresses
- access and address
> Adding sections on addresses

- content/courses/ada-idioms/chapters/inheritance_idioms.rst
- content/courses/ada-idioms/index.rst
Based on document written by Patrick Rogers.
> Adding section on using building blocks to express inheritance idioms

- frontend/py_modules/code_projects/check_projects.py
> Test script: making JSON file discovery easier

- content/courses/ada-idioms/chapters/constructor_functions_for_type_extensions.rst
add alternative of using nested package, and argue against doing so
> add alternative of using a nested package

- frontend/Makefile
Excluding extraneous JSON files
> Makefile: minor fix to output ZIP file

- content/courses/ada-idioms/chapters/component_access_to_rec_objs.rst
> misc refinements and a typo

- content/hidden_contents.txt
Adding hidden indices to the list.
> Editorial change: updating list of hidden files

- content/courses/ada-idioms/chapters/programming_by_extension.rst
- content/courses/ada-idioms/index.rst
Renaming: "Accommodating Future Enhancements" => "Programming by Extension"
> Editorial change: renaming chapter

- content/courses/Guidelines_for_Safe_and_Secure_Ada_SPARK/chapters/guidelines/dynamic_storage_management/dyn05_user-defined_storage_pools_policy.rst
Integrating comment by Tucker Taft.
> Mentioning enforcement by specifying Default_Storage_Pool

- content/courses/advanced-ada/parts/resource_management/controlled_types.rst
- content/courses/advanced-ada/parts/resource_management/index_hidden.rst
- content/courses/advanced-ada/parts/resource_management/memory_management.rst
Also: new section on memory subpools
> Editorial changes: new chapter on controlled types

- frontend/Makefile
- Improvements to "make help" command.
- Based on GitHub gist: https://gist.github.com/prwhite/8168133
> Makefile: improving help messages

- content/courses/ada-idioms/chapters/constructor_functions_for_abstract_data_types.rst
- content/courses/ada-idioms/chapters/controlling_obj_initialization_creation.rst
- content/courses/ada-idioms/chapters/programming_by_extension.rst
- content/courses/ada-idioms/index.rst
Chapter was written by Pat Rogers.
> Adding chapter: "Controlling Object Initialization and Creation"

- content/index.rst
Course: "Guidelines for Safe and Secure Ada/SPARK"
> Editorial change: adding course to the list for publication

- content/courses/advanced-ada/parts/resource_management/limited_types.rst
Integrating comments and changes suggested by Patrick Rogers.
> Various improvements to chapter on limited types

- content/courses/advanced-ada/parts/data_types/records.rst
- content/courses/advanced-ada/parts/resource_management/access_types.rst
Integrating suggestions by Tucker Taft.
> Improvements to section on per-object expressions

- content/courses/advanced-ada/changelog.rst
- content/courses/advanced-ada/index.rst
- New separate CHANGELOG file
- Adding release notes for previous releases
> Improving CHANGELOG

- content/courses/advanced-ada/parts/data_types/types.rst
- content/courses/advanced-ada/parts/resource_management/limited_types.rst
Various improvements and corrections to the chapter.
> Review chapter: "Limited Types"

- frontend/webpack.common.js
> Frontend: using "fullhash"

- content/courses/advanced-ada/parts/resource_management/anonymous_access_types.rst
- content/courses/advanced-ada/parts/resource_management/limited_types.rst
- Improving code examples
- Using references
> Minor editorial changes

- content/courses/advanced-ada/parts/resource_management/limited_types.rst
> Fix typo limited_types.rst

- content/courses/ada-idioms/chapters/type_punning.rst
also renamed integer type to Acceleration for clarity
> various polishing

- frontend/sphinx/widget/templates/widget.html
- frontend/src/styles/learn.scss
- frontend/src/ts/strings.ts
- frontend/src/ts/widget.ts
- frontend/tests/ts/widget.spec.ts
> Widget: fix dangerous menu options

- frontend/py_modules/code_projects/toolchain.ini
> Test script: updating to latest GNAT-14 version

- frontend/src/styles/_variables.scss
- frontend/src/styles/learn.scss
- frontend/src/ts/strings.ts
> Labs: improving visibility of test cases details

- content/labs/intro-to-ada/chapters/subprograms.rst
> Improve description of lab exercise

- content/courses/advanced-ada/parts/data_types/arrays.rst
Also: improving section on array constraints.
> Adding section on derived array types and array subtypes

- content/courses/ada-idioms/chapters/introduction.rst
Thoroughly revised the introduction section of the introductory chapter.
Some polishing in the Compile-time Visibility section of that same chapter.
> Revised Introduction chapter to clarify the purpose of the course and nature of the idiom entries.

- .github/workflows/codeql-analysis.yml
This reverts commit 796989ca86304f494d17b20c90a8318882a65da0.
> Revert "GitHub actions: reintroducing testing on "push""

- frontend/sphinx/widget_extension.py
Getting rid of deprecation warning for next major Sphinx version.
> Sphinx: using method from Tags module

- content/courses/advanced-ada/parts/data_types/numerics.rst
Move section ("Numeric Literal") up to the beginning of the chapter.
> Editorial change: move section up

- content/courses/Ada_For_The_CPP_Java_Developer/index.rst
- content/courses/Ada_For_The_Embedded_C_Developer/index.rst
- content/courses/GNAT_Toolchain_Intro/index.rst
- content/courses/Guidelines_for_Safe_and_Secure_Ada_SPARK/index.rst
- content/courses/SPARK_for_the_MISRA_C_Developer/index.rst
- content/courses/ada-in-practice/index.rst
- content/courses/advanced-ada/index.rst
- content/courses/advanced-ada/index_hidden.rst
- content/courses/advanced-spark/index.rst
- content/courses/intro-to-ada/index.rst
- content/courses/intro-to-embedded-sys-prog/index.rst
- content/courses/intro-to-spark/index.rst
- content/courses/whats-new-in-ada-2022/index.rst
- content/index.rst
- content/labs/bug-free-coding/index.rst
- content/labs/intro-to-ada/index.rst
> Sphinx: add meta tags to prevent indexing by robots

- frontend/src/index.ts
- frontend/src/ts/sandbox-redirect.ts
- frontend/src/ts/staging.ts
> Frontend: introducing password/cookie-based authentication for learn-sandbox
