AdaCore/learn

requirements.txt

Add Ipython, needed to run the tests. Bump to the more recent
stable release of Sphinx.

Adjust requirements

---

engine/sphinx/widget_extension.py

Do this by getting the order from the gnatchop output.

Preserve the order of files in example snippets

---

engine/sphinx/widget_extension.py

This is the template that accepts all configurations of
with or without SPARK and with or without a main.

Use the template "Inline Code" always

---

courses/intro-to-ada/chapters/exceptions.rst

This was actually already fixed in a previous commit (IDs:
d40678d94ac5bee67feae9cd977fc2ace2c55005,
53e3d2d51622459617f7694dadd050e8f933736d)
https://github.com/AdaCore/learn/pull/55

Editorial change: removed ReST class due to dependency

---

courses/intro-to-ada/chapters/standard_library.rst

Converted 'code' to 'code-block'.

Editorial change: removed 'run' button for file I/O examples

---

engine/sphinx/conf.py

That way the sidebar doesn't scroll together with the content, and the
logo & search bar stays visible

Disable sticky_navigation

---

engine/sphinx/learn_theme/static/js/editors.js

This fixes an issue where relaunching an operation after
an error causes some lines to be ignored in the new run.

Reset lines already read when launching an operation

---

.travis.yml

Due to Sphinx warning from 'ace-builds' module.

Travis-CI: deactivating git submodules

---

books/SPARK_for_the_MISRA_C_Developer/chapters/02_program_consistency.rst
courses/intro-to-spark/book/05_Proof_Of_Functional_Correctness.rst
engine/sphinx/widget_extension.py

Getting rid of raw HTML ('pre') output.
Corrected two source-code blocks.
Fixed issue #163.

Using widget for 'ada-nocheck' and 'ada-syntax-only' classes

---

engine/Makefile
engine/sphinx/conf.py
engine/sphinx/widget_extension.py

Bump the copyright year, make the URL of the code server
read an environment variable, and add a Makefile target
for regenerating a build of the site pointing to a local
code server.

Minor adjustments, useful for the development environment

---

engine/sphinx/learn_theme/static/css/common.css

Rearrange margins around containers so that highlight boxes
don't have a blank space at the bottom.
Re-add top borders to the editors.

Minor CSS fixes

---

books/SPARK_for_the_MISRA_C_Developer/chapters/06_side_effects.rst

Fix closing quote. Also fix strange asymmetry in ``X1 - X2`` displayed
as 'X1 -X2' in pdf. Remove space to avoid the asymmetry.

Minor fixes from Piotr's review

---

courses/intro-to-spark/book/05_Proof_Of_Functional_Correctness.rst

... as the indentation is needed to identify the main.

S628-014 Fix indentation of SPARK snippets

---

courses/intro-to-spark/book/01_Overview.rst
courses/intro-to-spark/book/02_Flow_Analysis.rst
courses/intro-to-spark/book/03_Proof_Of_Program_Integrity.rst
courses/intro-to-spark/book/04_State_Abstraction.rst
courses/intro-to-spark/book/05_Proof_Of_Functional_Correctness.rst

Due to changes in the default used in the engine for the SPARK course, many
interactive snippets were missing a prove button. Now fixed.
Also fixes minor issues of parasitic warnings and less-than-ideal buttons.
Also modifies examples in reaction to improvements in flow analysis now
detecting correctly initialization of unconstrained array around loops.

Restore prove buttons in SPARK intro course

---

books/SPARK_for_the_MISRA_C_Developer/chapters/03_syntactic_guarantees.rst
books/SPARK_for_the_MISRA_C_Developer/chapters/04_strong_typing.rst
books/SPARK_for_the_MISRA_C_Developer/chapters/05_initialization.rst
books/SPARK_for_the_MISRA_C_Developer/chapters/06_side_effects.rst
books/SPARK_for_the_MISRA_C_Developer/chapters/07_undefined_behavior.rst

Add qualifier ada-syntax-only when no main is provided.
Add parameter prove_report_all_button when we'd like the messages about
proved checks.
Uniformly use ERROR in comments to signal violations of Ada or SPARK rules.

Various fixes on the interactive snippets

---

engine/Makefile

site: make the 'real' site pointing to cloudchecker.r53.adacore.com
publish: publish what's in _build to learn.adacore.com

Add Makefile targets

---

courses/intro-to-ada/chapters/tasking.rst

This should highlight that developers may use multiple "accepts" in
"select ... or".

Changed source-code example to use two entries instead of just one

---

backend/app/__init__.py
backend/app/widget/container.py
backend/app/widget/file.py
backend/app/widget/lab.py
backend/app/widget/project.py
backend/app/widget/reporter.py
backend/app/widget/tasks.py
backend/config/settings.py
frontend/Makefile

This fixes excessive logging by celery which was taxing the server in situations where apps heavily used TEXT_IO. The logging has been modified to only write to logs when there are log levels at WARNING or above.

Logging fix

---

frontend/src/ts/widget.ts

Fixing selection issue in output area. If text is selected, focus won't jump to the offending line in the editor. If nothing is selected, focus will jump as usual.

Fixing issue #321

---

frontend/src/ts/components.ts
frontend/src/ts/editor.ts
frontend/src/ts/widget.ts

Fixing useability issue when changing tabs in a widget. If editors were different sizes, changing tabs would cause the editor to shink or expand making it difficult to use. This fix will make the minimum size of each editor in the widget equal to the largest length editor in the grouping.

Fixing editor resize between tab changes

---

content/courses/SPARK_for_the_MISRA_C_Developer/chapters/03_syntactic_guarantees.rst
content/courses/SPARK_for_the_MISRA_C_Developer/chapters/04_strong_typing.rst
content/courses/SPARK_for_the_MISRA_C_Developer/chapters/05_initialization.rst
content/courses/SPARK_for_the_MISRA_C_Developer/chapters/06_side_effects.rst

Should use new feature from PR#334
It still seems there is no Examine(report=all) on all snippets that have
prove_flow_report_all_button, maybe due to the use of code-config above
with prove_button=False. To be sorted out.

Use new compile_button that replaces class ada-syntax-only

---

frontend/Makefile

The step to copy the generated pdf books to the publishing repo was missing from the publish Makefile target.

Fixing publish Makefile target to include copy of pdf_books to target.

---

content/courses/intro-to-ada/chapters/modular_programming.rst

Text below the example used `T.Put_Line`, but the example renames to `TIO`.

Corrected "T.Put_Line" to "TIO.Put_Line"

---

content/courses/intro-to-ada/chapters/subprograms.rst

The documentation talks about _parameter modes_, but the section discussing them used _parameters modes_. I changed the latter.

Changed "parameters mode" to singular to match rest of documentation

---

content/courses/Ada_For_The_C_Embedded_Developer/conf.txt
content/courses/intro-to-ada/conf.txt
content/courses/intro-to-spark/conf.txt

- Using "\\and" markup as suggested in Sphinx documentation
(https://www.sphinx-doc.org/en/2.0/usage/configuration.html)
- This change fixes #466.

Editorial change: using LaTeX markup for separating authors.

---

backend/app/widget/project.py

This was a backend error that assumed the the "main" key was explicitly added to every incoming request.

Fixing download for widgets without a explicit specified main.

---

.github/workflows/sphinx-content-tests.js.yml
content/courses/Ada_For_The_Embedded_C_Developer/chapters/01_Introduction.rst
content/courses/Ada_For_The_Embedded_C_Developer/chapters/02_Perspective.rst
content/courses/Ada_For_The_Embedded_C_Developer/chapters/03_Concurrency.rst
content/courses/Ada_For_The_Embedded_C_Developer/chapters/04_Embedded.rst
content/courses/Ada_For_The_Embedded_C_Developer/chapters/08_Performance.rst
content/courses/intro-to-ada/chapters/arrays.rst
content/courses/intro-to-ada/chapters/exceptions.rst
content/courses/intro-to-ada/chapters/generics.rst
content/courses/intro-to-ada/chapters/imperative_language.rst
content/courses/intro-to-ada/chapters/modular_programming.rst
content/courses/intro-to-ada/chapters/more_about_types.rst
content/courses/intro-to-ada/chapters/object_oriented_programming.rst
content/courses/intro-to-ada/chapters/privacy.rst
content/courses/intro-to-ada/chapters/records.rst
content/courses/intro-to-ada/chapters/standard_library_containers.rst
content/courses/intro-to-ada/chapters/standard_library_files_streams.rst
content/courses/intro-to-ada/chapters/standard_library_numerics.rst
content/courses/intro-to-ada/chapters/strongly_typed_language.rst
content/courses/intro-to-ada/chapters/subprograms.rst
content/courses/intro-to-ada/chapters/tasking.rst
frontend/Makefile
frontend/sphinx/code_block_info.py
frontend/sphinx/widget/widget.py
frontend/sphinx/widget_extension.py
frontend/tests/compile_blocks.py

- Test script: adding support for storing build / runtime output, including: C-code blocks, blocks with prover button.
- Sphinx: using "ada-run" for code blocks that don't have run button.
- Proof-of-concept: fixing all issues found in PDF version of the "Introduction to Ada" course.
- GitHub actions: adding support for storing PDF books as artifact.

Introducing initial support for compile-time / runtime output for PDF books

---

content/courses/Ada_For_The_Embedded_C_Developer/chapters/02_Perspective.rst
content/courses/Ada_For_The_Embedded_C_Developer/chapters/04_Embedded.rst
content/courses/Ada_For_The_Embedded_C_Developer/chapters/06_Translation.rst
content/courses/Ada_For_The_Embedded_C_Developer/chapters/07_Reusability.rst
content/courses/Ada_For_The_Embedded_C_Developer/chapters/08_Performance.rst
content/courses/SPARK_for_the_MISRA_C_Developer/chapters/02_program_consistency.rst
content/courses/SPARK_for_the_MISRA_C_Developer/chapters/04_strong_typing.rst
frontend/Makefile
frontend/sphinx/conf.py
frontend/sphinx/widget_extension.py
frontend/tests/compile_blocks.py

- Printing line numbers for all source-code examples of PDF books.
- Removing to-do items from PDF books.
- Updating release date.
- Fixing source-code examples ("return 0" was missing).
- Including runtime output for some examples without run button (using "ada-run" class).
- Removing some paragraphs containing "hard-coded" compiler output.
- Removing "summary logged in" line from prover output.

Solving remaining issues for PDF books.

---

backend/app/widget/project.py

Empty mains were causing "no main found" errors in the backend.

Fixing unspecified main failures.

---

content/labs/bug-free-coding/chapters/stack.rst

The purpose of the stack lab is to use output from the prover to
complete the stack. Add a note to that effect to remind the user,
so that they are not surprised to see errors when they click
Prove.

Add note that lab/stack proof errors are expected

---

frontend/sphinx/widget_extension.py
frontend/tests/ts/widget.spec.ts

The new URL provides an updated cloudchecker service with GNAT Community
2021 installed.
TN: U604-038

Update cloudchecker-staging URL

---

frontend/Makefile

The new URL provides an updated cloudchecker service with GNAT Community
2021 installed.
TN: U604-038

Update cloudchecker URL

---

content/courses/SPARK_for_the_MISRA_C_Developer/chapters/04_strong_typing.rst

Correct references to illegality of pointers in SPARK. Rather, SPARK
analysis tool accepts pointers and detects problematic constructs now.

Refresh content of SPARK-for-MISRA-C-Developer guide

---

content/courses/intro-to-spark/chapters/01_Overview.rst

General access types are now allowed in SPARK.
Replace this violation by a use of controlled types.

Update code examples to changes in SPARK

---

frontend/sphinx/widget/chop.py

Displaying code with line numbers.

Sphinx: printing code in case of gnatchop error

---

content/courses/whats-new-in-ada-2022/chapters/array_aggregates.rst
content/courses/whats-new-in-ada-2022/chapters/assignment_target.rst
content/courses/whats-new-in-ada-2022/chapters/image_attribute.rst
content/courses/whats-new-in-ada-2022/chapters/importing_variadic_functions.rst
content/courses/whats-new-in-ada-2022/chapters/introduction.rst

* content/courses/whats-new-in-ada-2022/chapters/array_aggregates.rst
Fix text as iterated component associations are allowed to mix with other
associations.
* content/courses/whats-new-in-ada-2022/chapters/assignment_target.rst
Fix hyphen.
* content/courses/whats-new-in-ada-2022/chapters/image_attribute.rst
Fix plural.
* courses/whats-new-in-ada-2022/chapters/importing_variadic_functions.rst
Remove Next button on last chapter.
* content/courses/whats-new-in-ada-2022/chapters/introduction.rst
Fix typo.

Minor fixes for the course on what's new in Ada 2022

---

content/courses/Ada_For_The_CPP_Java_Developer/chapters/05_Type_System.rst

According to C++ standards parameterless profile looks like
`()` not like `(void)`.

Drop `void` in C++ profile

---

content/courses/Ada_For_The_Embedded_C_Developer/chapters/02_Perspective.rst
content/courses/Ada_For_The_Embedded_C_Developer/chapters/05_SPARK.rst
content/courses/Ada_For_The_Embedded_C_Developer/chapters/08_Performance.rst
content/courses/intro-to-spark/chapters/01_Overview.rst
content/courses/intro-to-spark/chapters/04_State_Abstraction.rst
content/courses/intro-to-spark/chapters/05_Proof_Of_Functional_Correctness.rst

Some code blocks were pulling in files that they shouldn't have been because they shared a project name with a code block that they shouldn't have.
Some tests were also failing due to missing failure expectations

Fix some code blocks

---

frontend/src/ts/widget.ts

Currently when a user presses a button, to execute some task, multiple times in quick succession, this can cause messages from multiple executions to appear in the output area.
~~This change should prevent this from happening, with only the output from the final press being displayed~~
This change makes it so that when any execute button is pressed, all execute buttons for that code block are disabled until the task is complete.

Prevent user from spamming execute buttons

---

.github/workflows/sphinx-books-tests.js.yml
content/index.rst
frontend/Makefile
frontend/sphinx/code_block_info.py
frontend/sphinx/widget_extension.py
frontend/tests/code_block.py
frontend/tests/compile_blocks.py

- Writing separate directories for code blocks.
- Directories named by MD5 hash.
- Writing JSON file containing code block information.
Ref #626

Infrastructure: adding support for zipfile with source-code examples

---

frontend/src/styles/learn.scss

This issue caused the dropout menu to be hidden behind the surrounding text.

Widget: fixing overlap issue for dropout menu

---

content/courses/Ada_For_The_Embedded_C_Developer/chapters/02_Perspective.rst

Editorial change: replacing by correct word

---

frontend/package.json
frontend/src/ts/widget.ts

When the frontend receives a responses from the backend, it tries to find the file which relates to the message. If it finds a file it then decorate the line with the message, rather than just printing the message to the homeArea as normal.
But there are cases where the file name/line number is found, but the file is not available in the view (e.g. #937), which was causing a backend error message to be erroneously displayed. Now in cases where it doesn't find the file it just prints the message to the homeArea.
This change also simplifies the logic for performing this highlighting, and increases the number of cases it's able to highlight. For example, cases like
```
raised INTERNAL_EXCEPTIONS.INT_E : show_exception_renaming_view.adb:8
raised CONSTRAINT_ERROR : …
```

Fix backend error being shown by mistake, which was hiding actual result

---

content/courses/ada-idioms/chapters/component_access_to_rec_objs.rst

clarify why both ADTs need a discrim designating a USART

remove extra blank and wordsmithing

---

content/courses/intro-to-ada/chapters/interfacing_with_c.rst

Rename: strlcpy => strlcpy_stat.
Avoid conflict with standard function.

Editorial change: renaming strlcpy

---

content/courses/Ada_For_The_CPP_Java_Developer/chapters/08_Classes_and_Object_Oriented_Programming.rst

In the Java code block, `I2` should be an interface instead of a class (because `Child` _implements_ `I2`) and the methods `M2` and `M3` should use Java syntax instead of C++ syntax.

Fix Java example code

---

content/courses/ada-idioms/chapters/component_access_to_rec_objs.rst
content/courses/ada-idioms/chapters/constructor_functions_for_type_extensions.rst

Change the title and motivation summary for the constructors idiom to say it is about ADTs, not just type extensions.
Refine the component access idiom to give example for immutably limited types, etc.

Various refinements

---

content/index.rst
frontend/src/styles/learn.scss

The current layout is too big for the growing number of books on Learn, the latest books are too far down the page. The goal of this patch is to have more e-books (covers and download buttons) displayed on the screen using a compact layout.

Use a more compact layout for the front page ebook covers

---

frontend/package.json

Warnings are false positives, as those types indicated in the warnings should be known by the compiler.

Frontend: avoid jsdoc warnings about undefined types

---

Vagrantfile

Aligning with implementation for epub VM.

Vagrant VM: using toolchain information from configuration file

---

content/courses/intro-to-ada/chapters/standard_library_strings.rst

Improving introductory paragraph on unbounded strings

---

content/courses/ada-idioms/chapters/type_punning.rst

Clarified need for "aliased" regarding register assignment by compiler. Added paragraph saying that the example ignored endianess issue. Clarified that it is "Buffer (0)'Address" that is the same as "Buffer'Address".

Further polishing.

---

content/courses/ada-idioms/chapters/abstract_data_machines.rst
content/courses/ada-idioms/chapters/abstract_data_types.rst
content/courses/ada-idioms/chapters/component_access_to_rec_objs.rst
content/courses/ada-idioms/chapters/constructor_functions_for_abstract_data_types.rst
content/courses/ada-idioms/chapters/controlling_obj_initialization_creation.rst
content/courses/ada-idioms/chapters/introduction.rst
content/courses/ada-idioms/chapters/programming_by_extension.rst

Here are some editorial suggestions for the Ada Idioms course.  I have reviewed about six of the idioms.

Initial editorial suggestions from T. Taft

---

content/courses/ada-idioms/chapters/abstract_data_machines.rst

Added motivation section and thoroughly revised the entire entry for clarity and brevity.

Adding motivation section.

---

content/courses/ada-idioms/chapters/abstract_data_machines.rst

Minor wordsmithing of one sentence.

Add missing punctuation.

---

content/courses/GNAT_Toolchain_Intro/chapters/gnat_tools.rst

gnatmetric is not available anymore.

Remove section on gnatmetric

---

Vagrantfile

Replace archive.ubuntu.com and security.ubuntu.com by old-releases.ubuntu.com for Ubuntu 23.10 installation.

Vagrant VM: use old-releases repo for Ubuntu installation

---

frontend/src/ts/download.ts

`gprbuild` ignores `Default_Switches` when there is `Switches` clause. Gprbuild guide says:
> Value is a list of switches to be used when invoking the compiler
> for the language for a source of the project,
> if **there is no applicable attribute** Switches.
On the other side `Default_Switches` confuseis GNAT Studio.
Fix #1166

Drop `Default_Switches` from project files.

---

content/courses/advanced-ada/parts/resource_management/access_types.rst

Fixes null access exceptions for example in advanced Ada / Resource Management / Access Types / Access Type Abstraction example when calling `Copy` (both versions) with a `Info = null`

Fix for null access support in example

---

content/courses/ada-idioms/chapters/type_punning.rst

When entries have multiple implementations, remove text from each header that "numbers" the implementations

Use consistent scheme for multiple implementations

---

content/courses/ada-idioms/chapters/abstract_data_machines.rst
content/courses/ada-idioms/chapters/abstract_data_types.rst
content/courses/ada-idioms/chapters/appendices.rst
content/courses/ada-idioms/chapters/component_access_to_rec_objs.rst
content/courses/ada-idioms/index.rst
content/hidden.txt
content/hidden_contents.txt
content/index.rst

Preparations for publication of "Ada Idioms" course
- Remove trailing whitespaces
- Update copyright year
- Exclude "Appendices" chapter
- Add course to list of published courses

Editorial change: various changes to "Ada Idioms" course

---

content/courses/advanced-ada/parts/data_types/aggregates.rst
content/courses/advanced-ada/parts/data_types/shared_variable_control.rst

Adding subsection on Full_Access_Only aspect

---

content/courses/ada-in-practice/chapters/raii.rst
content/courses/ada-in-practice/index.rst
content/courses/ada-in-practice/references.bib

Section was written by Patrick Rogers.

Adding section on Resource Acquisition Is Initialization (RAII)

---

content/courses/ada-in-practice/chapters/streams_api_flexibility.rst

Stress that streams can contain values of multiple types by definition, so this is as type-safe as can be.
Do some minor formatting and polishing.

Enhance the Cons section to say this is as type-safe as streams can be.
